version: "3.7"
name: async-api-test

services:
  movies-api:
    build: movies_api
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - .env.example

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      retries: 5

  functional-tests:
    build: tests
    env_file:
      - tests/functional/.env.example
    depends_on:
      - movies-api
